import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
const inter = Inter({ subsets: ["latin"] });
import { GlobalContextProvider } from "./context/page";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<GlobalContextProvider>
				<body className={inter.className}>
					<Navbar></Navbar>
					{children}
				</body>
			</GlobalContextProvider>
		</html>
	);
}
